// Auto-generated by build-notebook.js — do not edit manually.
// Source: myNotebookData/<Label>/*.json  (subfolder name = label)
// Labels: Week_2
// Total : 221 question(s) across 1 label(s)
//
// To update: edit files in myNotebookData/ then run:
//   node build-notebook.js
const NOTEBOOK_DATA = {
  "Week_2": {
    "questions": [
      {
        "id": "seed-1",
        "question": "What is the meaning of |新|?",
        "choices": [
          "new",
          "old",
          "big",
          "small"
        ],
        "answer": "new",
        "explanation": "新 (しん / あたら) means 'new'. Appears in: 新しい (new), 新聞 (newspaper), 最新 (latest).",
        "label": "Week_2"
      },
      {
        "id": "seed-2",
        "question": "How to read |新しい|くるまですね?",
        "choices": [
          "あたらしい",
          "あだらしい",
          "あらたしい",
          "あらだしい"
        ],
        "answer": "あたらしい",
        "explanation": "新しい is read あたらしい. Watch out — it is NOT あらたしい (a common mistake).",
        "label": "Week_2"
      },
      {
        "id": "seed-3",
        "question": "|学校|へ行きます。 What does 学校 mean?",
        "choices": [
          "school",
          "library",
          "hospital",
          "station"
        ],
        "answer": "school",
        "explanation": "学校 (がっこう) = school. 学 = study/learning, 校 = school.",
        "label": "Week_2"
      },
      {
        "id": "seed-4",
        "question": "How to read |車|?",
        "choices": [
          "くるま",
          "うま",
          "とり",
          "いぬ"
        ],
        "answer": "くるま",
        "explanation": "車 = くるま (car/vehicle). On'yomi: しゃ (used in compounds like 自動車 jidousha).",
        "label": "Week_2"
      },
      {
        "id": "seed-5",
        "question": "毎日 |日本語| を べんきょうします。 What is 日本語?",
        "choices": [
          "Japanese language",
          "Chinese language",
          "English language",
          "Korean language"
        ],
        "answer": "Japanese language",
        "explanation": "日本語 (にほんご) = Japanese language. 日本 (Japan) + 語 (language).",
        "label": "Week_2"
      },
      {
        "id": "seed-6",
        "question": "What is the meaning of |山|?",
        "choices": [
          "mountain",
          "river",
          "sea",
          "sky"
        ],
        "answer": "mountain",
        "explanation": "山 (やま / さん) = mountain. Famous example: 富士山 (ふじさん) = Mt. Fuji.",
        "label": "Week_2"
      },
      {
        "id": "seed-7",
        "question": "What is the meaning of |人|?",
        "choices": [
          "person",
          "child",
          "friend",
          "family"
        ],
        "answer": "person",
        "explanation": "人 (ひと / じん / にん) = person. 日本人 (にほんじん) = Japanese person, 三人 (さんにん) = 3 people.",
        "label": "Week_2"
      },
      {
        "id": "seed-8",
        "question": "What is the meaning of |円|?",
        "choices": [
          "yen / circle",
          "money in general",
          "coin",
          "ticket"
        ],
        "answer": "yen / circle",
        "explanation": "円 (えん) = yen, the Japanese currency. Original meaning is 'circle' (まるい). 千円 (せんえん) = 1000 yen.",
        "label": "Week_2"
      },
      {
        "id": "seed-9",
        "question": "How to read |9時|?",
        "choices": [
          "くじ",
          "きゅうじ",
          "ここのじ",
          "きゅじ"
        ],
        "answer": "くじ",
        "explanation": "⚠ Watch out: 9時 = くじ, NOT きゅうじ. Three time-reading exceptions to memorize: 4時=よじ, 7時=しちじ, 9時=くじ.",
        "label": "Week_2"
      },
      {
        "id": "seed-10",
        "question": "How to read |4時|?",
        "choices": [
          "よじ",
          "しじ",
          "よんじ",
          "よっじ"
        ],
        "answer": "よじ",
        "explanation": "⚠ 4時 = よじ. Even though 4 is usually よん or し, in time you say よじ.",
        "label": "Week_2"
      },
      {
        "id": "seed-11",
        "question": "How to read |7時|?",
        "choices": [
          "しちじ",
          "ななじ",
          "しっじ",
          "なのじ"
        ],
        "answer": "しちじ",
        "explanation": "7時 = しちじ. 7 has two readings (しち / なな), but in time it is しち.",
        "label": "Week_2"
      },
      {
        "id": "seed-12",
        "question": "What day is |月曜日|?",
        "choices": [
          "Monday",
          "Sunday",
          "Saturday",
          "Friday"
        ],
        "answer": "Monday",
        "explanation": "月曜日 (げつようび) = Monday. The 月 here means 'moon' (the planet), like 'Moon-day' in English.",
        "label": "Week_2"
      },
      {
        "id": "seed-13",
        "question": "How to read |水曜日|?",
        "choices": [
          "すいようび",
          "みずようび",
          "みずようひ",
          "すいよび"
        ],
        "answer": "すいようび",
        "explanation": "水曜日 (すいようび) = Wednesday. 水 = water (すい in compounds, みず alone).",
        "label": "Week_2"
      },
      {
        "id": "seed-14",
        "question": "How to read |土曜日|?",
        "choices": [
          "どようび",
          "つちようび",
          "とようび",
          "どうようび"
        ],
        "answer": "どようび",
        "explanation": "土曜日 (どようび) = Saturday. 土 in compounds is ど (not つち).",
        "label": "Week_2"
      },
      {
        "id": "seed-15",
        "question": "Choose the correct particle: 7時(___)おきます。",
        "choices": [
          "に",
          "で",
          "を",
          "へ"
        ],
        "answer": "に",
        "explanation": "に marks a specific point in time. 7時に = at 7 o'clock. Note: do NOT add に after 今日 / 昨日 / 明日 / 毎日.",
        "label": "Week_2"
      },
      {
        "id": "seed-16",
        "question": "Choose the correct particle: でんしゃ(___)がっこうへ いきます。",
        "choices": [
          "で",
          "に",
          "を",
          "と"
        ],
        "answer": "で",
        "explanation": "で marks the means/method (here: transportation). でんしゃで = by train. Exception: 歩いて (on foot) does NOT take で.",
        "label": "Week_2"
      },
      {
        "id": "seed-17",
        "question": "Choose the correct particle: ともだち(___)えいがを みます。",
        "choices": [
          "と",
          "に",
          "で",
          "から"
        ],
        "answer": "と",
        "explanation": "と means 'together with (a person)'. ともだちと = with a friend. Used for the person you do something with.",
        "label": "Week_2"
      },
      {
        "id": "seed-18",
        "question": "Choose the correct particle: わたしは とうきょう(___)いきます。",
        "choices": [
          "へ",
          "で",
          "を",
          "から"
        ],
        "answer": "へ",
        "explanation": "へ marks direction/destination of movement. に also works here, but へ is more strongly tied to direction. Read as 'え', not 'へ'.",
        "label": "Week_2"
      },
      {
        "id": "seed-19",
        "question": "Choose the correct particles: わたし(A)ほん(B)よみます。",
        "choices": [
          "A=は, B=を",
          "A=を, B=は",
          "A=は, B=に",
          "A=が, B=を"
        ],
        "answer": "A=は, B=を",
        "explanation": "は marks the topic (the person/thing the sentence is about). を marks the direct object of an action verb.",
        "label": "Week_2"
      },
      {
        "id": "seed-20",
        "question": "What is the past affirmative form of |たべます|?",
        "choices": [
          "たべました",
          "たべませんでした",
          "たべません",
          "たべて"
        ],
        "answer": "たべました",
        "explanation": "ます form conjugation: ます (present) → ました (past) → ません (negative) → ませんでした (past negative).",
        "label": "Week_2"
      },
      {
        "id": "seed-21",
        "question": "What is the past negative form of |いきます|?",
        "choices": [
          "いきませんでした",
          "いきません",
          "いきました",
          "いかない"
        ],
        "answer": "いきませんでした",
        "explanation": "Past negative = ませんでした. So いきます → いきませんでした (did not go).",
        "label": "Week_2"
      },
      {
        "id": "seed-22",
        "question": "What does |おきます| mean?",
        "choices": [
          "wake up / get up",
          "go to bed",
          "go out",
          "come home"
        ],
        "answer": "wake up / get up",
        "explanation": "おきます (起きます) = wake up. Pair with ねます (寝ます) = go to bed.",
        "label": "Week_2"
      },
      {
        "id": "seed-23",
        "question": "What is |電車|?",
        "choices": [
          "train",
          "car",
          "bus",
          "bicycle"
        ],
        "answer": "train",
        "explanation": "電車 (でんしゃ) = (electric) train. 電 = electricity, 車 = vehicle.",
        "label": "Week_2"
      },
      {
        "id": "seed-24",
        "question": "|毎日| べんきょうします。 What does 毎日 mean?",
        "choices": [
          "every day",
          "today",
          "tomorrow",
          "yesterday"
        ],
        "answer": "every day",
        "explanation": "毎日 (まいにち) = every day. Note: do NOT add に after 毎日 — say 毎日 おきます, not 毎日に おきます.",
        "label": "Week_2"
      },
      {
        "id": "seed-25",
        "question": "|何時| ですか。 What does 何時 mean?",
        "choices": [
          "what time",
          "what day",
          "how long",
          "how much"
        ],
        "answer": "what time",
        "explanation": "何時 (なんじ) = what time. 何 (なん/なに) = what + 時 (じ) = hour.",
        "label": "Week_2"
      },
      {
        "id": "seed-26",
        "question": "これは |いくら| ですか。 What does いくら mean?",
        "choices": [
          "how much (price)",
          "how many",
          "what color",
          "what kind"
        ],
        "answer": "how much (price)",
        "explanation": "いくら = how much (used for price). Standard reply: 〜円です. Example: 500円です.",
        "label": "Week_2"
      },
      {
        "id": "seed-27",
        "question": "Choose the correct particles: 9時(A)5時(B)はたらきます。",
        "choices": [
          "A=から, B=まで",
          "A=まで, B=から",
          "A=に, B=に",
          "A=で, B=へ"
        ],
        "answer": "A=から, B=まで",
        "explanation": "から = from (start point), まで = until (end point). Works for both time and place: とうきょうから おおさかまで.",
        "label": "Week_2"
      },
      {
        "id": "w2-001",
        "question": "What is the meaning of |一|?",
        "choices": [
          "one",
          "two",
          "three",
          "ten"
        ],
        "answer": "one",
        "explanation": "一 = one. Readings: いち (on'yomi), ひと (kun, as in 一つ ひとつ = one item).",
        "label": "Week_2"
      },
      {
        "id": "w2-002",
        "question": "What is the meaning of |二|?",
        "choices": [
          "two",
          "four",
          "six",
          "eight"
        ],
        "answer": "two",
        "explanation": "二 = two. Readings: に / ふた (二つ ふたつ = two items).",
        "label": "Week_2"
      },
      {
        "id": "w2-003",
        "question": "What is the meaning of |三|?",
        "choices": [
          "three",
          "five",
          "seven",
          "nine"
        ],
        "answer": "three",
        "explanation": "三 = three. Readings: さん / みっ (三つ みっつ = three items).",
        "label": "Week_2"
      },
      {
        "id": "w2-004",
        "question": "What is the meaning of |五|?",
        "choices": [
          "five",
          "four",
          "six",
          "eight"
        ],
        "answer": "five",
        "explanation": "五 = five. Readings: ご / いつ (五つ いつつ = five items).",
        "label": "Week_2"
      },
      {
        "id": "w2-005",
        "question": "What is the meaning of |七|?",
        "choices": [
          "seven",
          "five",
          "nine",
          "ten"
        ],
        "answer": "seven",
        "explanation": "七 = seven. Readings: しち / なな. In time, use しち (7時=しちじ).",
        "label": "Week_2"
      },
      {
        "id": "w2-006",
        "question": "What is the meaning of |九|?",
        "choices": [
          "nine",
          "seven",
          "six",
          "ten"
        ],
        "answer": "nine",
        "explanation": "九 = nine. Readings: く / きゅう. In time, use く (9時=くじ, NOT きゅうじ).",
        "label": "Week_2"
      },
      {
        "id": "w2-007",
        "question": "What is the meaning of |十|?",
        "choices": [
          "ten",
          "one",
          "thousand",
          "hundred"
        ],
        "answer": "ten",
        "explanation": "十 = ten. Readings: じゅう / とお (十日 とおか = the 10th).",
        "label": "Week_2"
      },
      {
        "id": "w2-008",
        "question": "What is the meaning of |日|?",
        "choices": [
          "day, sun",
          "month, moon",
          "year",
          "week"
        ],
        "answer": "day, sun",
        "explanation": "日 = day or sun. Readings: にち / ひ. 日本 (にほん) = Japan ('origin of the sun').",
        "label": "Week_2"
      },
      {
        "id": "w2-009",
        "question": "What is the meaning of |月|?",
        "choices": [
          "month, moon",
          "day, sun",
          "year",
          "fire"
        ],
        "answer": "month, moon",
        "explanation": "月 = month or moon. Readings: げつ / がつ / つき.",
        "label": "Week_2"
      },
      {
        "id": "w2-010",
        "question": "What is the meaning of |火|?",
        "choices": [
          "fire",
          "water",
          "tree",
          "earth"
        ],
        "answer": "fire",
        "explanation": "火 = fire. Readings: か / ひ. Used in 火曜日 (かようび) = Tuesday.",
        "label": "Week_2"
      },
      {
        "id": "w2-011",
        "question": "What is the meaning of |水|?",
        "choices": [
          "water",
          "fire",
          "wood",
          "gold"
        ],
        "answer": "water",
        "explanation": "水 = water. Readings: すい / みず. Used in 水曜日 (すいようび) = Wednesday.",
        "label": "Week_2"
      },
      {
        "id": "w2-012",
        "question": "What is the meaning of |木|?",
        "choices": [
          "tree, wood",
          "earth",
          "mountain",
          "fire"
        ],
        "answer": "tree, wood",
        "explanation": "木 = tree or wood. Readings: もく / き. Used in 木曜日 (もくようび) = Thursday.",
        "label": "Week_2"
      },
      {
        "id": "w2-013",
        "question": "What is the meaning of |金|?",
        "choices": [
          "gold, money",
          "silver, water",
          "tree, wood",
          "earth, soil"
        ],
        "answer": "gold, money",
        "explanation": "金 = gold or money. Readings: きん / かね. お金 (おかね) = money. 金曜日 = Friday.",
        "label": "Week_2"
      },
      {
        "id": "w2-014",
        "question": "What is the meaning of |土|?",
        "choices": [
          "earth, soil",
          "water",
          "fire",
          "wood"
        ],
        "answer": "earth, soil",
        "explanation": "土 = earth or soil. Readings: ど / つち. Used in 土曜日 (どようび) = Saturday.",
        "label": "Week_2"
      },
      {
        "id": "w2-017",
        "question": "How to read |山| alone?",
        "choices": [
          "やま",
          "さん",
          "かわ",
          "うみ"
        ],
        "answer": "やま",
        "explanation": "山 alone = やま. In compounds, often さん (富士山 ふじさん = Mt. Fuji).",
        "label": "Week_2"
      },
      {
        "id": "w2-018",
        "question": "How to read |水| alone?",
        "choices": [
          "みず",
          "すい",
          "ひ",
          "き"
        ],
        "answer": "みず",
        "explanation": "水 alone = みず (water). In compounds: すい (水曜日 すいようび).",
        "label": "Week_2"
      },
      {
        "id": "w2-019",
        "question": "How to read |火| alone?",
        "choices": [
          "ひ",
          "か",
          "ほ",
          "ね"
        ],
        "answer": "ひ",
        "explanation": "火 alone = ひ (fire). In compounds: か (火曜日 かようび).",
        "label": "Week_2"
      },
      {
        "id": "w2-020",
        "question": "How to read |木| alone?",
        "choices": [
          "き",
          "もく",
          "ぎ",
          "こ"
        ],
        "answer": "き",
        "explanation": "木 alone = き (tree). In compounds: もく (木曜日 もくようび).",
        "label": "Week_2"
      },
      {
        "id": "w2-021",
        "question": "How to read |お金|?",
        "choices": [
          "おかね",
          "おきん",
          "おかな",
          "おがね"
        ],
        "answer": "おかね",
        "explanation": "お金 (おかね) = money. The お is an honorific prefix. 金 alone = かね.",
        "label": "Week_2"
      },
      {
        "id": "w2-022",
        "question": "How to read |日本|?",
        "choices": [
          "にほん",
          "にっぽん",
          "Both にほん and にっぽん are correct",
          "にちほん"
        ],
        "answer": "Both にほん and にっぽん are correct",
        "explanation": "日本 can be read either にほん or にっぽん. Both are official. にほん is more common in daily speech.",
        "label": "Week_2"
      },
      {
        "id": "w2-023",
        "question": "How to read |日本人|?",
        "choices": [
          "にほんじん",
          "にほんひと",
          "にっぽんにん",
          "にちほんじん"
        ],
        "answer": "にほんじん",
        "explanation": "日本人 (にほんじん) = Japanese person. 人 in nationality compounds is じん.",
        "label": "Week_2"
      },
      {
        "id": "w2-024",
        "question": "How to read |三人|?",
        "choices": [
          "さんにん",
          "さんじん",
          "さんひと",
          "みんにん"
        ],
        "answer": "さんにん",
        "explanation": "三人 (さんにん) = three people. Counter for people uses にん from 4 onwards. Exceptions: 一人 ひとり, 二人 ふたり.",
        "label": "Week_2"
      },
      {
        "id": "w2-025",
        "question": "How to read |一人|?",
        "choices": [
          "ひとり",
          "いちにん",
          "いちじん",
          "いっぴと"
        ],
        "answer": "ひとり",
        "explanation": "⚠ Exception: 一人 = ひとり (one person), NOT いちにん. Means both 'one person' and 'alone'.",
        "label": "Week_2"
      },
      {
        "id": "w2-026",
        "question": "How to read |二人|?",
        "choices": [
          "ふたり",
          "ににん",
          "ふたにん",
          "にじん"
        ],
        "answer": "ふたり",
        "explanation": "⚠ Exception: 二人 = ふたり (two people). Often used to mean 'a couple'.",
        "label": "Week_2"
      },
      {
        "id": "w2-027",
        "question": "How to read |四人|?",
        "choices": [
          "よにん",
          "しにん",
          "よんにん",
          "よっにん"
        ],
        "answer": "よにん",
        "explanation": "四人 = よにん (four people). 4 in counters often uses よ/よん, not し (し sounds like 死 = death).",
        "label": "Week_2"
      },
      {
        "id": "w2-028",
        "question": "How to read |千円|?",
        "choices": [
          "せんえん",
          "ちえん",
          "せんねん",
          "ちえん"
        ],
        "answer": "せんえん",
        "explanation": "千円 (せんえん) = 1000 yen. 千 = せん (thousand).",
        "label": "Week_2"
      },
      {
        "id": "w2-029",
        "question": "How to read |三つ|?",
        "choices": [
          "みっつ",
          "さんつ",
          "みつ",
          "さんっつ"
        ],
        "answer": "みっつ",
        "explanation": "三つ (みっつ) = three (general counter). The general counter uses kun-yomi: 一つ ひとつ, 二つ ふたつ, 三つ みっつ, 四つ よっつ...",
        "label": "Week_2"
      },
      {
        "id": "w2-030",
        "question": "How to read |四つ|?",
        "choices": [
          "よっつ",
          "よつ",
          "しつ",
          "よんつ"
        ],
        "answer": "よっつ",
        "explanation": "四つ (よっつ) = four (general counter).",
        "label": "Week_2"
      },
      {
        "id": "w2-031",
        "question": "How to read |1時|?",
        "choices": [
          "いちじ",
          "ひとじ",
          "いっじ",
          "いちとき"
        ],
        "answer": "いちじ",
        "explanation": "1時 = いちじ (1 o'clock).",
        "label": "Week_2"
      },
      {
        "id": "w2-035",
        "question": "How to read |10時半|?",
        "choices": [
          "じゅうじはん",
          "じゅっじはん",
          "とおじはん",
          "じゅうとき はん"
        ],
        "answer": "じゅうじはん",
        "explanation": "10時半 (じゅうじはん) = 10:30. 半 (はん) = half (used for :30).",
        "label": "Week_2"
      },
      {
        "id": "w2-036",
        "question": "How to read |4月|?",
        "choices": [
          "しがつ",
          "よがつ",
          "よんがつ",
          "よげつ"
        ],
        "answer": "しがつ",
        "explanation": "⚠ Months and time exceptions are different! 4月 = しがつ (April). Compare: 4時 = よじ.",
        "label": "Week_2"
      },
      {
        "id": "w2-037",
        "question": "How to read |7月|?",
        "choices": [
          "しちがつ",
          "ななつき",
          "ななかつ",
          "しちつき"
        ],
        "answer": "しちがつ",
        "explanation": "7月 = しちがつ (July). All months use がつ + on'yomi number.",
        "label": "Week_2"
      },
      {
        "id": "w2-038",
        "question": "How to read |9月|?",
        "choices": [
          "くがつ",
          "きゅうがつ",
          "ここのがつ",
          "くうがつ"
        ],
        "answer": "くがつ",
        "explanation": "⚠ 9月 = くがつ (September), NOT きゅうがつ. Same trick as 9時 = くじ.",
        "label": "Week_2"
      },
      {
        "id": "w2-039",
        "question": "How to read |30分|?",
        "choices": [
          "さんじゅっぷん",
          "さんじゅうふん",
          "さんとお ふん",
          "さんじゅうぶん"
        ],
        "answer": "さんじゅっぷん",
        "explanation": "30分 (さんじゅっぷん) = 30 minutes. Also written さんじっぷん. Equivalent to 半 (はん).",
        "label": "Week_2"
      },
      {
        "id": "w2-040",
        "question": "How to read |午前|?",
        "choices": [
          "ごぜん",
          "ごご",
          "あさ",
          "ひる"
        ],
        "answer": "ごぜん",
        "explanation": "午前 (ごぜん) = AM, morning. 午後 (ごご) = PM, afternoon.",
        "label": "Week_2"
      },
      {
        "id": "w2-041",
        "question": "How to read |月曜日|?",
        "choices": [
          "げつようび",
          "がつようび",
          "つきようび",
          "げつようひ"
        ],
        "answer": "げつようび",
        "explanation": "月曜日 (げつようび) = Monday. 月 here = moon (Mon = Moon-day).",
        "label": "Week_2"
      },
      {
        "id": "w2-042",
        "question": "How to read |火曜日|?",
        "choices": [
          "かようび",
          "ひようび",
          "ほようび",
          "かようひ"
        ],
        "answer": "かようび",
        "explanation": "火曜日 (かようび) = Tuesday. 火 = fire (Mars in planets, Mardi in French).",
        "label": "Week_2"
      },
      {
        "id": "w2-044",
        "question": "How to read |木曜日|?",
        "choices": [
          "もくようび",
          "きようび",
          "ぼくようび",
          "もくようひ"
        ],
        "answer": "もくようび",
        "explanation": "木曜日 (もくようび) = Thursday. 木 = wood (Jupiter in planets).",
        "label": "Week_2"
      },
      {
        "id": "w2-045",
        "question": "How to read |金曜日|?",
        "choices": [
          "きんようび",
          "かねようび",
          "ぎんようび",
          "きんようひ"
        ],
        "answer": "きんようび",
        "explanation": "金曜日 (きんようび) = Friday. 金 = gold (Venus in planets, Vendredi in French).",
        "label": "Week_2"
      },
      {
        "id": "w2-047",
        "question": "How to read |日曜日|?",
        "choices": [
          "にちようび",
          "ひようび",
          "にっようび",
          "にちようひ"
        ],
        "answer": "にちようび",
        "explanation": "日曜日 (にちようび) = Sunday. 日 = sun (Sun-day).",
        "label": "Week_2"
      },
      {
        "id": "w2-048",
        "question": "今日は |何曜日| ですか? — What is being asked?",
        "choices": [
          "What day of the week",
          "What time",
          "What date",
          "What month"
        ],
        "answer": "What day of the week",
        "explanation": "何曜日 (なんようび) = what day of the week. Reply: 月曜日です, 火曜日です, etc.",
        "label": "Week_2"
      },
      {
        "id": "w2-049",
        "question": "If today is 水曜日, what day is tomorrow (明日)?",
        "choices": [
          "木曜日",
          "火曜日",
          "金曜日",
          "月曜日"
        ],
        "answer": "木曜日",
        "explanation": "水曜日 (Wed) → 木曜日 (Thu). Order: 月→火→水→木→金→土→日.",
        "label": "Week_2"
      },
      {
        "id": "w2-050",
        "question": "If today is 月曜日, what day was yesterday (昨日)?",
        "choices": [
          "日曜日",
          "火曜日",
          "土曜日",
          "金曜日"
        ],
        "answer": "日曜日",
        "explanation": "月曜日 (Mon) ← 日曜日 (Sun). Sunday comes before Monday.",
        "label": "Week_2"
      },
      {
        "id": "w2-051",
        "question": "Choose the correct particle: わたし(___)がくせいです。",
        "choices": [
          "は",
          "が",
          "を",
          "に"
        ],
        "answer": "は",
        "explanation": "は marks the topic. わたしは = 'as for me / I am'. Pronounced 'wa', not 'ha'.",
        "label": "Week_2"
      },
      {
        "id": "w2-052",
        "question": "Choose the correct particle: パン(___)たべます。",
        "choices": [
          "を",
          "は",
          "に",
          "で"
        ],
        "answer": "を",
        "explanation": "を marks the direct object of an action verb. パンを たべます = (I) eat bread. Pronounced 'o'.",
        "label": "Week_2"
      },
      {
        "id": "w2-053",
        "question": "Choose the correct particle: 6時(___)おきます。",
        "choices": [
          "に",
          "で",
          "へ",
          "から"
        ],
        "answer": "に",
        "explanation": "に marks a specific point in time (with clock times, days, dates).",
        "label": "Week_2"
      },
      {
        "id": "w2-054",
        "question": "Choose the correct particle: バス(___)いきます。",
        "choices": [
          "で",
          "に",
          "を",
          "と"
        ],
        "answer": "で",
        "explanation": "で marks the means/method (here: by bus). Exception: 歩いて (on foot) takes NO particle.",
        "label": "Week_2"
      },
      {
        "id": "w2-055",
        "question": "Choose the correct particle: かいしゃ(___)いきます。",
        "choices": [
          "へ",
          "で",
          "を",
          "から"
        ],
        "answer": "へ",
        "explanation": "へ (read 'え') marks direction of movement. に also works; へ emphasizes direction more.",
        "label": "Week_2"
      },
      {
        "id": "w2-056",
        "question": "Choose the correct particle: かぞく(___)ばんごはんを たべます。",
        "choices": [
          "と",
          "に",
          "で",
          "を"
        ],
        "answer": "と",
        "explanation": "と = 'together with (a person)'. かぞくと = with (my) family.",
        "label": "Week_2"
      },
      {
        "id": "w2-058",
        "question": "Choose the correct particle: とうきょう(___)おおさかまで しんかんせんで いきます。",
        "choices": [
          "から",
          "まで",
          "に",
          "で"
        ],
        "answer": "から",
        "explanation": "から marks the starting point (place). Pair with まで (until/to).",
        "label": "Week_2"
      },
      {
        "id": "w2-059",
        "question": "Which sentence is INCORRECT?",
        "choices": [
          "まいにちに べんきょうします。",
          "まいにち べんきょうします。",
          "7時に おきます。",
          "土曜日に いきます。"
        ],
        "answer": "まいにちに べんきょうします。",
        "explanation": "⚠ Do NOT add に after まいにち, きょう, あした, きのう, いま. These already imply time on their own.",
        "label": "Week_2"
      },
      {
        "id": "w2-061",
        "question": "Choose the correct particles: わたし(A)みず(B)のみます。",
        "choices": [
          "A=は, B=を",
          "A=を, B=は",
          "A=は, B=に",
          "A=が, B=を"
        ],
        "answer": "A=は, B=を",
        "explanation": "は (topic) + を (direct object). Standard SOV pattern: Subject は, Object を, Verb.",
        "label": "Week_2"
      },
      {
        "id": "w2-062",
        "question": "Choose the correct particles: ともだち(A)えいが(B)みます。",
        "choices": [
          "A=と, B=を",
          "A=を, B=と",
          "A=に, B=を",
          "A=で, B=を"
        ],
        "answer": "A=と, B=を",
        "explanation": "ともだちと (with a friend) + えいがを (movie as object) みます (watch).",
        "label": "Week_2"
      },
      {
        "id": "w2-063",
        "question": "Choose the correct particle: これは いくら(___)か?",
        "choices": [
          "です",
          "ます",
          "ません",
          "でした"
        ],
        "answer": "です",
        "explanation": "Question pattern with noun + question word: いくらですか = how much is (it)?",
        "label": "Week_2"
      },
      {
        "id": "w2-064",
        "question": "Which particle marks the topic of a sentence?",
        "choices": [
          "は",
          "を",
          "に",
          "で"
        ],
        "answer": "は",
        "explanation": "は marks the topic. The topic is what the sentence is 'about'. Pronounced 'wa' as a particle.",
        "label": "Week_2"
      },
      {
        "id": "w2-065",
        "question": "Which particle marks the direct object of a verb?",
        "choices": [
          "を",
          "は",
          "に",
          "へ"
        ],
        "answer": "を",
        "explanation": "を marks what receives the action of the verb. パンを たべます, ほんを よみます.",
        "label": "Week_2"
      },
      {
        "id": "w2-066",
        "question": "Which particle marks the means / method (e.g., transportation, tools)?",
        "choices": [
          "で",
          "に",
          "へ",
          "と"
        ],
        "answer": "で",
        "explanation": "で marks how something is done (by train, with chopsticks, in Japanese).",
        "label": "Week_2"
      },
      {
        "id": "w2-068",
        "question": "What is the negative form (present) of |のみます|?",
        "choices": [
          "のみません",
          "のみました",
          "のみませんでした",
          "のまない"
        ],
        "answer": "のみません",
        "explanation": "ます → ません = present negative. 'do not drink'.",
        "label": "Week_2"
      },
      {
        "id": "w2-070",
        "question": "What is the past affirmative of |ねます|?",
        "choices": [
          "ねました",
          "ねません",
          "ねませんでした",
          "ねた"
        ],
        "answer": "ねました",
        "explanation": "ねます → ねました = slept.",
        "label": "Week_2"
      },
      {
        "id": "w2-071",
        "question": "What is the present negative of |おきます|?",
        "choices": [
          "おきません",
          "おきました",
          "おきませんでした",
          "おきない"
        ],
        "answer": "おきません",
        "explanation": "おきます → おきません = do not wake up.",
        "label": "Week_2"
      },
      {
        "id": "w2-072",
        "question": "What is the past negative of |よみます|?",
        "choices": [
          "よみませんでした",
          "よみません",
          "よみました",
          "よまない"
        ],
        "answer": "よみませんでした",
        "explanation": "よみます → よみませんでした = did not read.",
        "label": "Week_2"
      },
      {
        "id": "w2-073",
        "question": "Choose the correct sentence for: 'I read a book yesterday.'",
        "choices": [
          "きのう ほんを よみました。",
          "きのう ほんを よみます。",
          "あした ほんを よみました。",
          "きのう ほんを よみません。"
        ],
        "answer": "きのう ほんを よみました。",
        "explanation": "きのう = yesterday → past tense → よみました.",
        "label": "Week_2"
      },
      {
        "id": "w2-074",
        "question": "Choose the correct sentence for: 'I do not eat breakfast.'",
        "choices": [
          "あさごはんを たべません。",
          "あさごはんを たべました。",
          "あさごはんを たべませんでした。",
          "あさごはんを たべます。"
        ],
        "answer": "あさごはんを たべません。",
        "explanation": "Habitual present negative = ません.",
        "label": "Week_2"
      },
      {
        "id": "w2-075",
        "question": "Choose the correct sentence for: 'I did not work on Sunday.'",
        "choices": [
          "にちようび はたらきませんでした。",
          "にちようび はたらきません。",
          "にちようび はたらきました。",
          "にちようびに はたらきませんでした。"
        ],
        "answer": "にちようび はたらきませんでした。",
        "explanation": "Past negative + day of week. Note: に is optional after days of the week, but never used after まいにち / きょう / あした.",
        "label": "Week_2"
      },
      {
        "id": "w2-076",
        "question": "What is the dictionary meaning of |おきます|?",
        "choices": [
          "wake up / get up",
          "go to bed",
          "go out",
          "come home"
        ],
        "answer": "wake up / get up",
        "explanation": "起きます (おきます) = wake up. Opposite: ねます (sleep).",
        "label": "Week_2"
      },
      {
        "id": "w2-077",
        "question": "What is the dictionary meaning of |ねます|?",
        "choices": [
          "go to bed / sleep",
          "wake up",
          "rest",
          "stand up"
        ],
        "answer": "go to bed / sleep",
        "explanation": "寝ます (ねます) = go to bed, sleep.",
        "label": "Week_2"
      },
      {
        "id": "w2-078",
        "question": "What is the dictionary meaning of |いきます|?",
        "choices": [
          "go",
          "come",
          "return",
          "leave"
        ],
        "answer": "go",
        "explanation": "行きます (いきます) = go. Pair with きます (come) and かえります (return).",
        "label": "Week_2"
      },
      {
        "id": "w2-079",
        "question": "What is the dictionary meaning of |きます|?",
        "choices": [
          "come",
          "go",
          "return",
          "wear"
        ],
        "answer": "come",
        "explanation": "来ます (きます) = come. Watch out: also used for 着ます (wear) — different kanji, same kana.",
        "label": "Week_2"
      },
      {
        "id": "w2-080",
        "question": "What is the dictionary meaning of |かえります|?",
        "choices": [
          "return home / go back",
          "come",
          "go",
          "stay"
        ],
        "answer": "return home / go back",
        "explanation": "帰ります (かえります) = return (home or to one's base place). Different from もどります (return generally).",
        "label": "Week_2"
      },
      {
        "id": "w2-081",
        "question": "What is the dictionary meaning of |たべます|?",
        "choices": [
          "eat",
          "drink",
          "buy",
          "make"
        ],
        "answer": "eat",
        "explanation": "食べます (たべます) = eat.",
        "label": "Week_2"
      },
      {
        "id": "w2-082",
        "question": "What is the dictionary meaning of |のみます|?",
        "choices": [
          "drink",
          "eat",
          "smoke",
          "swallow"
        ],
        "answer": "drink",
        "explanation": "飲みます (のみます) = drink. Also used for taking medicine: くすりを のみます.",
        "label": "Week_2"
      },
      {
        "id": "w2-083",
        "question": "What is the dictionary meaning of |よみます|?",
        "choices": [
          "read",
          "write",
          "say",
          "listen"
        ],
        "answer": "read",
        "explanation": "読みます (よみます) = read.",
        "label": "Week_2"
      },
      {
        "id": "w2-084",
        "question": "What is the dictionary meaning of |みます|?",
        "choices": [
          "watch / see",
          "listen",
          "read",
          "look for"
        ],
        "answer": "watch / see",
        "explanation": "見ます (みます) = see, watch, look at.",
        "label": "Week_2"
      },
      {
        "id": "w2-085",
        "question": "What is the dictionary meaning of |ききます|?",
        "choices": [
          "listen / hear / ask",
          "read",
          "watch",
          "speak"
        ],
        "answer": "listen / hear / ask",
        "explanation": "聞きます (ききます) = listen, hear. Also means 'ask (a question)'.",
        "label": "Week_2"
      },
      {
        "id": "w2-086",
        "question": "What is the dictionary meaning of |はたらきます|?",
        "choices": [
          "work",
          "study",
          "rest",
          "play"
        ],
        "answer": "work",
        "explanation": "働きます (はたらきます) = work (at a job). Different from べんきょうします (study).",
        "label": "Week_2"
      },
      {
        "id": "w2-087",
        "question": "What is the dictionary meaning of |やすみます|?",
        "choices": [
          "rest / take a day off",
          "study",
          "work",
          "wake up"
        ],
        "answer": "rest / take a day off",
        "explanation": "休みます (やすみます) = rest, take a day off. かいしゃを やすみます = take off work.",
        "label": "Week_2"
      },
      {
        "id": "w2-088",
        "question": "What is the meaning of |電車|?",
        "choices": [
          "train",
          "car",
          "bus",
          "bicycle"
        ],
        "answer": "train",
        "explanation": "電車 (でんしゃ) = (electric) train. 電 = electricity, 車 = vehicle.",
        "label": "Week_2"
      },
      {
        "id": "w2-089",
        "question": "What is the meaning of |自転車|?",
        "choices": [
          "bicycle",
          "motorcycle",
          "car",
          "scooter"
        ],
        "answer": "bicycle",
        "explanation": "自転車 (じてんしゃ) = bicycle. Literally 'self-rotating vehicle'.",
        "label": "Week_2"
      },
      {
        "id": "w2-090",
        "question": "What is the meaning of |新幹線|?",
        "choices": [
          "bullet train",
          "regular train",
          "subway",
          "tram"
        ],
        "answer": "bullet train",
        "explanation": "新幹線 (しんかんせん) = Shinkansen, the high-speed bullet train.",
        "label": "Week_2"
      },
      {
        "id": "w2-091",
        "question": "What is the meaning of |飛行機|?",
        "choices": [
          "airplane",
          "helicopter",
          "ship",
          "rocket"
        ],
        "answer": "airplane",
        "explanation": "飛行機 (ひこうき) = airplane. 飛 = fly, 行 = go, 機 = machine.",
        "label": "Week_2"
      },
      {
        "id": "w2-092",
        "question": "What is the meaning of |駅|?",
        "choices": [
          "station (train)",
          "airport",
          "bus stop",
          "port"
        ],
        "answer": "station (train)",
        "explanation": "駅 (えき) = train station. Common word: 東京駅 (とうきょうえき) = Tokyo Station.",
        "label": "Week_2"
      },
      {
        "id": "w2-093",
        "question": "What is the meaning of |会社|?",
        "choices": [
          "company / workplace",
          "school",
          "store",
          "bank"
        ],
        "answer": "company / workplace",
        "explanation": "会社 (かいしゃ) = company. 会社員 (かいしゃいん) = company employee.",
        "label": "Week_2"
      },
      {
        "id": "w2-094",
        "question": "What is the meaning of |毎日|?",
        "choices": [
          "every day",
          "today",
          "tomorrow",
          "yesterday"
        ],
        "answer": "every day",
        "explanation": "毎日 (まいにち) = every day. Note: do NOT add に (まいにち おきます, NOT まいにちに おきます).",
        "label": "Week_2"
      },
      {
        "id": "w2-095",
        "question": "What is the meaning of |今|?",
        "choices": [
          "now",
          "today",
          "soon",
          "later"
        ],
        "answer": "now",
        "explanation": "今 (いま) = now, the present moment. Different from きょう (today).",
        "label": "Week_2"
      },
      {
        "id": "w2-096",
        "question": "Where is the closest meaning of |ここ|?",
        "choices": [
          "here (near me)",
          "there (near you)",
          "over there (far)",
          "where"
        ],
        "answer": "here (near me)",
        "explanation": "こ-そ-あ-ど system: ここ (here, near speaker), そこ (there, near listener), あそこ (over there, far from both), どこ (where).",
        "label": "Week_2"
      },
      {
        "id": "w2-097",
        "question": "What does |あそこ| mean?",
        "choices": [
          "over there (far from both speakers)",
          "here",
          "there (near you)",
          "somewhere"
        ],
        "answer": "over there (far from both speakers)",
        "explanation": "あそこ refers to a place far from both speaker and listener. Note: irregular — it's あそこ, not あこ.",
        "label": "Week_2"
      },
      {
        "id": "w2-098",
        "question": "What does |いくら| mean?",
        "choices": [
          "how much (price)",
          "how many",
          "how long",
          "what"
        ],
        "answer": "how much (price)",
        "explanation": "いくら = how much (specifically for price). Reply pattern: 〜円です.",
        "label": "Week_2"
      },
      {
        "id": "w2-099",
        "question": "Pick the correct translation: 'I drink coffee every morning.'",
        "choices": [
          "まいあさ コーヒーを のみます。",
          "まいあさに コーヒーを のみました。",
          "まいあさ コーヒーが のみます。",
          "まいあさ コーヒーを のみません。"
        ],
        "answer": "まいあさ コーヒーを のみます。",
        "explanation": "まいあさ (every morning) takes no に. Object コーヒー takes を. Habitual present = ます.",
        "label": "Week_2"
      },
      {
        "id": "w2-100",
        "question": "Pick the correct translation: 'I went to school by bicycle yesterday.'",
        "choices": [
          "きのう じてんしゃで がっこうへ いきました。",
          "きのう じてんしゃに がっこうへ いきました。",
          "あした じてんしゃで がっこうへ いきます。",
          "きのう じてんしゃで がっこうを いきました。"
        ],
        "answer": "きのう じてんしゃで がっこうへ いきました。",
        "explanation": "Means of transport = で. Direction = へ. Past tense = ました.",
        "label": "Week_2"
      },
      {
        "id": "w2-101",
        "question": "Pick the correct translation: 'How much is this?'",
        "choices": [
          "これは いくらですか。",
          "これは なんですか。",
          "これは どこですか。",
          "これは いつですか。"
        ],
        "answer": "これは いくらですか。",
        "explanation": "いくら = how much (price). なん = what, どこ = where, いつ = when.",
        "label": "Week_2"
      },
      {
        "id": "w2-102",
        "question": "Pick the correct translation: 'I do not work on Saturdays.'",
        "choices": [
          "どようび はたらきません。",
          "どようびに はたらきます。",
          "どようび はたらきました。",
          "どようび はたらきませんでした。"
        ],
        "answer": "どようび はたらきません。",
        "explanation": "Habitual present negative. Days of the week may take に optionally; here omitted.",
        "label": "Week_2"
      },
      {
        "id": "w2-103",
        "question": "What time is being said: 'いま、ごご よじはん です。'",
        "choices": [
          "4:30 PM",
          "4:30 AM",
          "4:00 PM",
          "14:30 (military)"
        ],
        "answer": "4:30 PM",
        "explanation": "ごご = PM, よじ = 4 o'clock, はん = half (30). So 4:30 PM.",
        "label": "Week_2"
      },
      {
        "id": "w2-104",
        "question": "Read this sentence: 'まいばん 11時に ねます。' What does it mean?",
        "choices": [
          "I go to bed at 11 PM every night.",
          "I wake up at 11 AM every morning.",
          "I went to bed at 11 yesterday.",
          "I will sleep at 11 tomorrow."
        ],
        "answer": "I go to bed at 11 PM every night.",
        "explanation": "まいばん = every night (note: まいばん takes に for the time, but まいばん itself does not). 11時に ねます = sleep at 11.",
        "label": "Week_2"
      },
      {
        "id": "w2-105",
        "question": "Read this dialogue: 'A: なんようびに いきますか。 B: ___ いきます。' Which is most natural?",
        "choices": [
          "きんようびに",
          "きんようびで",
          "きんようびを",
          "きんようびへ"
        ],
        "answer": "きんようびに",
        "explanation": "Days of the week take に when used as a time marker (matches the question's に). Other particles don't fit this slot.",
        "label": "Week_2"
      },
      {
        "id": "auto_1",
        "question": "Choose the correct reading for the kanji |四時|.",
        "choices": [
          "しじ",
          "よんじ",
          "よじ",
          "よっじ"
        ],
        "answer": "よじ",
        "explanation": "According to the Week 2 syllabus, 4:00 is a specific exception and must be pronounced as よじ (yoji).",
        "label": "Week_2"
      },
      {
        "id": "auto_2",
        "question": "Which particle is used to indicate a |means of transport|, such as in 'でんしゃ... いきます'?",
        "choices": [
          "に",
          "へ",
          "で",
          "を"
        ],
        "answer": "で",
        "explanation": "The particle で is used to denote the means or method of transportation.",
        "label": "Week_2"
      },
      {
        "id": "auto_3",
        "question": "Identify the correct negative past form of |べんきょうします|.",
        "choices": [
          "べんきょうしません",
          "べんきょうしました",
          "べんきょうしませでした",
          "べんきょうしませんでした"
        ],
        "answer": "べんきょうしませんでした",
        "explanation": "The negative past form of ます verbs is ませんでした.",
        "label": "Week_2"
      },
      {
        "id": "auto_4",
        "question": "What is the correct reading for |七時|?",
        "choices": [
          "ななじ",
          "しちじ",
          "ななじじ",
          "しじ"
        ],
        "answer": "しちじ",
        "explanation": "The syllabus notes that 7:00 is pronounced as しちじ (shichiji).",
        "label": "Week_2"
      },
      {
        "id": "auto_5",
        "question": "Complete the sentence: 'わたしは |あるいて| がっこうへ いきます。' Which particle follows |あるいて|?",
        "choices": [
          "で",
          "に",
          "を",
          "No particle needed"
        ],
        "answer": "No particle needed",
        "explanation": "As noted in the lesson, the term 歩いて (walking) is an exception and does not use the particle で.",
        "label": "Week_2"
      },
      {
        "id": "auto_6",
        "question": "Which kanji represents |Wednesday|?",
        "choices": [
          "月曜日",
          "火曜日",
          "水曜日",
          "木曜日"
        ],
        "answer": "水曜日",
        "explanation": "水曜日 (Suiyoubi) means Wednesday.",
        "label": "Week_2"
      },
      {
        "id": "auto_7",
        "question": "What is the reading of the kanji |九時|?",
        "choices": [
          "きゅうじ",
          "くじ",
          "ここのじ",
          "きゅうじじ"
        ],
        "answer": "くじ",
        "explanation": "9:00 is a designated exception in time-telling and is read as くじ (kuji).",
        "label": "Week_2"
      },
      {
        "id": "auto_8",
        "question": "Which particle indicates the |direction| or |destination| of movement?",
        "choices": [
          "を",
          "に",
          "へ",
          "で"
        ],
        "answer": "へ",
        "explanation": "The particle へ is used to indicate the direction or destination when using movement verbs like 行きます.",
        "label": "Week_2"
      },
      {
        "id": "auto_9",
        "question": "Translate: 'I wake up |at 7:00|.'",
        "choices": [
          "7じにおきます",
          "7じでおきます",
          "7じをおきます",
          "7じへおきます"
        ],
        "answer": "7じにおきます",
        "explanation": "The particle に is used to mark a specific point in time.",
        "label": "Week_2"
      },
      {
        "id": "auto_10",
        "question": "Choose the correct kanji for |Monday|.",
        "choices": [
          "日曜日",
          "月曜日",
          "金曜日",
          "土曜日"
        ],
        "answer": "月曜日",
        "explanation": "月曜日 (Getsuyoubi) represents Monday.",
        "label": "Week_2"
      },
      {
        "id": "auto_11",
        "question": "How do you say |10:30| in Japanese?",
        "choices": [
          "10じさんじゅっぷん",
          "10じはん",
          "10じはんぷん",
          "Both A and B"
        ],
        "answer": "Both A and B",
        "explanation": "Both ~じさんじゅっぷん and ~じはん (half past) are correct ways to express the half-hour.",
        "label": "Week_2"
      },
      {
        "id": "auto_12",
        "question": "Which verb means |to work|?",
        "choices": [
          "やすみます",
          "はたらきます",
          "おきます",
          "ねます"
        ],
        "answer": "はたらきます",
        "explanation": "はたらきます (hatarakimasu) translates to 'to work'.",
        "label": "Week_2"
      },
      {
        "id": "auto_13",
        "question": "What does |どこ| ask for?",
        "choices": [
          "Who",
          "What",
          "When",
          "Where"
        ],
        "answer": "Where",
        "explanation": "どこ (doko) is the interrogative for location.",
        "label": "Week_2"
      },
      {
        "id": "auto_14",
        "question": "Identify the kanji for |800 yen|.",
        "choices": [
          "八百円",
          "八百日",
          "八百人",
          "八百山"
        ],
        "answer": "八百円",
        "explanation": "円 (en) is the kanji for the Japanese currency, Yen.",
        "label": "Week_2"
      },
      {
        "id": "w2-015",
        "question": "Which particle means |'together with'| a person?",
        "choices": [
          "と",
          "に",
          "を",
          "へ"
        ],
        "answer": "と",
        "explanation": "The particle と is used to indicate the person with whom an action is performed.",
        "label": "Week_2"
      },
      {
        "id": "w2-016",
        "question": "What is the meaning of the verb |帰ります|?",
        "choices": [
          "To go",
          "To come",
          "To return home",
          "To stay"
        ],
        "answer": "To return home",
        "explanation": "帰ります (kaerimasu) specifically means to return back to one's home or base.",
        "label": "Week_2"
      },
      {
        "id": "auto_15",
        "question": "How is |6 minutes| pronounced?",
        "choices": [
          "ろくふん",
          "ろっぷん",
          "ろくぷん",
          "ろっふん"
        ],
        "answer": "ろっぷん",
        "explanation": "As per the rules for minutes, 6 minutes is pronounced as ろっぷん (roppun).",
        "label": "Week_2"
      },
      {
        "id": "auto_16",
        "question": "Identify the kanji for |Saturday|.",
        "choices": [
          "木曜日",
          "金曜日",
          "土曜日",
          "日曜日"
        ],
        "answer": "土曜日",
        "explanation": "土曜日 (Doyoubi) represents Saturday.",
        "label": "Week_2"
      },
      {
        "id": "auto_17",
        "question": "Which phrase is used to ask |'How much is this?'|",
        "choices": [
          "これはなんですか",
          "これはいくらですか",
          "これはどこですか",
          "これはだれですか"
        ],
        "answer": "これはいくらですか",
        "explanation": "いくら (ikura) is used to inquire about the price of an object.",
        "label": "Week_2"
      },
      {
        "id": "auto_18",
        "question": "Which particle marks the |direct object| of an action?",
        "choices": [
          "は",
          "を",
          "に",
          "で"
        ],
        "answer": "を",
        "explanation": "The particle を follows the noun that is the direct object of the verb.",
        "label": "Week_2"
      },
      {
        "id": "auto_19",
        "question": "What is the reading of |三階|?",
        "choices": [
          "さんがい",
          "さんかい",
          "みっかい",
          "ぞんがい"
        ],
        "answer": "さんがい",
        "explanation": "The counter for the 3rd floor (3階) changes to 'gai' for phonetic reasons: さんがい.",
        "label": "Week_2"
      },
      {
        "id": "auto_20",
        "question": "Identify the meaning of |あそこ|.",
        "choices": [
          "Here",
          "There",
          "Over there",
          "Where"
        ],
        "answer": "Over there",
        "explanation": "あそこ (asoko) refers to a location far from both the speaker and listener.",
        "label": "Week_2"
      },
      {
        "id": "auto_21",
        "question": "Which kanji means |'person'|?",
        "choices": [
          "日",
          "山",
          "人",
          "円"
        ],
        "answer": "人",
        "explanation": "人 (hito/jin) is the kanji for person.",
        "label": "Week_2"
      },
      {
        "id": "auto_22",
        "question": "What is the correct translation for |'Every day'|?",
        "choices": [
          "まいしゅう",
          "まいにち",
          "まいねん",
          "あした"
        ],
        "answer": "まいにち",
        "explanation": "まいにち (mainichi) means every day.",
        "label": "Week_2"
      },
      {
        "id": "auto_23",
        "question": "Which verb means |'to finish'| or |'to end'|?",
        "choices": [
          "はじまります",
          "おわります",
          "べんきょうします",
          "はたらきます"
        ],
        "answer": "おわります",
        "explanation": "おわります (owarimasu) means to end or finish.",
        "label": "Week_2"
      },
      {
        "id": "auto_24",
        "question": "Translate: 'From 9:00 |to| 5:00.'",
        "choices": [
          "9じから 5じに",
          "9じから 5じまで",
          "9じに 5じまで",
          "9じまで 5じから"
        ],
        "answer": "9じから 5じまで",
        "explanation": "から (from) and まで (until) are used to indicate time spans.",
        "label": "Week_2"
      },
      {
        "id": "auto_25",
        "question": "Which kanji represents |Tuesday|?",
        "choices": [
          "月曜日",
          "火曜日",
          "水曜日",
          "木曜日"
        ],
        "answer": "火曜日",
        "explanation": "火曜日 (Kayoubi) is Tuesday.",
        "label": "Week_2"
      },
      {
        "id": "auto_26",
        "question": "What is the meaning of |じむしょ|?",
        "choices": [
          "Classroom",
          "Office",
          "Reception",
          "Toilet"
        ],
        "answer": "Office",
        "explanation": "じむしょ (jimusho) refers to an office.",
        "label": "Week_2"
      },
      {
        "id": "auto_27",
        "question": "How do you read |五分|?",
        "choices": [
          "ごぷん",
          "ごふん",
          "いっふん",
          "いつふん"
        ],
        "answer": "ごふん",
        "explanation": "According to the minute reading rules, 5 minutes is pronounced ごふん (gofun).",
        "label": "Week_2"
      },
      {
        "id": "auto_28",
        "question": "What is the kanji for |mountain|?",
        "choices": [
          "人",
          "円",
          "山",
          "土"
        ],
        "answer": "山",
        "explanation": "山 (yama) is the kanji for mountain.",
        "label": "Week_2"
      },
      {
        "id": "auto_29",
        "question": "Identify the meaning of |うけつけ|.",
        "choices": [
          "Lobby",
          "Reception desk",
          "Room",
          "Staircase"
        ],
        "answer": "Reception desk",
        "explanation": "うけつけ (uketsuke) means the reception or information counter.",
        "label": "Week_2"
      },
      {
        "id": "w2-032",
        "question": "Which particle is used for |'Today'| in the sentence: 'Today I work'?",
        "choices": [
          "に",
          "を",
          "No particle needed",
          "で"
        ],
        "answer": "No particle needed",
        "explanation": "Relative time words like 今日 (kyou) do not take the particle に.",
        "label": "Week_2"
      },
      {
        "id": "w2-033",
        "question": "What is the reading of the kanji |六|?",
        "choices": [
          "ろく",
          "ご",
          "しち",
          "はち"
        ],
        "answer": "ろく",
        "explanation": "六 is the kanji for the number 6.",
        "label": "Week_2"
      },
      {
        "id": "w2-034",
        "question": "Which verb means |'to eat'|?",
        "choices": [
          "のみます",
          "たべます",
          "よみます",
          "みます"
        ],
        "answer": "たべます",
        "explanation": "たべます (tabemasu) is the verb for eating.",
        "label": "Week_2"
      },
      {
        "id": "auto_30",
        "question": "Translate: |'What day is it today?'|",
        "choices": [
          "きょうはなんじですか",
          "きょうはなんようびですか",
          "きょうはいくらですか",
          "きょうはどこですか"
        ],
        "answer": "きょうはなんようびですか",
        "explanation": "何曜日 (nanyoubi) is the interrogative used for days of the week.",
        "label": "Week_2"
      },
      {
        "id": "auto_31",
        "question": "Identify the past affirmative form of |ねます|.",
        "choices": [
          "ねます",
          "ねません",
          "ねました",
          "ねませんでした"
        ],
        "answer": "ねました",
        "explanation": "The past affirmative form of ます verbs is ました.",
        "label": "Week_2"
      },
      {
        "id": "auto_32",
        "question": "Which kanji represents |Thursday|?",
        "choices": [
          "火曜日",
          "水曜日",
          "木曜日",
          "金曜日"
        ],
        "answer": "木曜日",
        "explanation": "木曜日 (Mokuyoubi) is Thursday.",
        "label": "Week_2"
      },
      {
        "id": "auto_33",
        "question": "What is the meaning of |でんしゃ|?",
        "choices": [
          "Bus",
          "Taxi",
          "Train",
          "Bicycle"
        ],
        "answer": "Train",
        "explanation": "でんしゃ (densha) means electric train.",
        "label": "Week_2"
      },
      {
        "id": "auto_34",
        "question": "How do you read |八時|?",
        "choices": [
          "はちじ",
          "しちじ",
          "ろくじ",
          "くじ"
        ],
        "answer": "はちじ",
        "explanation": "八時 (hachiji) means 8:00.",
        "label": "Week_2"
      },
      {
        "id": "auto_35",
        "question": "Which verb means |'to read'|?",
        "choices": [
          "ききます",
          "みます",
          "よみます",
          "かきます"
        ],
        "answer": "よみます",
        "explanation": "よみます (yomimasu) means to read.",
        "label": "Week_2"
      },
      {
        "id": "auto_36",
        "question": "Which particle relates the |source and destination| in: 'うち... がっこうまで'?",
        "choices": [
          "に",
          "から",
          "で",
          "を"
        ],
        "answer": "から",
        "explanation": "から marks the starting point (from).",
        "label": "Week_2"
      },
      {
        "id": "auto_37",
        "question": "What is the reading of the kanji |十|?",
        "choices": [
          "いち",
          "じゅう",
          "く",
          "はち"
        ],
        "answer": "じゅう",
        "explanation": "十 is the kanji for the number 10.",
        "label": "Week_2"
      },
      {
        "id": "w2-043",
        "question": "Which kanji represents |Friday|?",
        "choices": [
          "火曜日",
          "水曜日",
          "金曜日",
          "土曜日"
        ],
        "answer": "金曜日",
        "explanation": "金曜日 (Kinyoubi) means Friday.",
        "label": "Week_2"
      },
      {
        "id": "auto_38",
        "question": "What does |いつ| mean?",
        "choices": [
          "Where",
          "Who",
          "When",
          "What"
        ],
        "answer": "When",
        "explanation": "いつ (itsu) is the interrogative for time.",
        "label": "Week_2"
      },
      {
        "id": "auto_39",
        "question": "Identify the meaning of |かばん|.",
        "choices": [
          "Shoes",
          "Watch",
          "Bag",
          "Umbrella"
        ],
        "answer": "Bag",
        "explanation": "かばん (kaban) means bag.",
        "label": "Week_2"
      },
      {
        "id": "w2-046",
        "question": "Which verb means |'to sleep'| or |'to go to bed'|?",
        "choices": [
          "おきます",
          "ねます",
          "たべます",
          "のみます"
        ],
        "answer": "ねます",
        "explanation": "ねます (nemasu) means to sleep.",
        "label": "Week_2"
      },
      {
        "id": "auto_40",
        "question": "How do you read |三分|?",
        "choices": [
          "さんふん",
          "さんぷん",
          "さっぷん",
          "みっぷん"
        ],
        "answer": "さんぷん",
        "explanation": "The reading rule for 3 minutes is さんぷん (sanpun).",
        "label": "Week_2"
      },
      {
        "id": "auto_41",
        "question": "Which kanji represents |Sunday|?",
        "choices": [
          "月曜日",
          "火曜日",
          "土曜日",
          "日曜日"
        ],
        "answer": "日曜日",
        "explanation": "日曜日 (Nichiyoubi) is Sunday.",
        "label": "Week_2"
      },
      {
        "id": "auto_42",
        "question": "Identify the meaning of |ひこうき|.",
        "choices": [
          "Ship",
          "Train",
          "Airplane",
          "Bus"
        ],
        "answer": "Airplane",
        "explanation": "ひこうき (hikouki) means airplane.",
        "label": "Week_2"
      },
      {
        "id": "auto_43",
        "question": "Which particle is used for |'by'| a specific method in: '日本語... はなします'?",
        "choices": [
          "に",
          "を",
          "で",
          "へ"
        ],
        "answer": "で",
        "explanation": "で is used to indicate the means or tool used for an action.",
        "label": "Week_2"
      },
      {
        "id": "auto_44",
        "question": "What is the reading of |二|?",
        "choices": [
          "いち",
          "に",
          "さん",
          "よん"
        ],
        "answer": "に",
        "explanation": "二 is the kanji for the number 2.",
        "label": "Week_2"
      },
      {
        "id": "auto_45",
        "question": "Which verb means |'to listen'|?",
        "choices": [
          "みます",
          "ききます",
          "よみます",
          "たべます"
        ],
        "answer": "ききます",
        "explanation": "ききます (kikimasu) means to listen.",
        "label": "Week_2"
      },
      {
        "id": "auto_46",
        "question": "Identify the meaning of |えき|.",
        "choices": [
          "Airport",
          "House",
          "Station",
          "Office"
        ],
        "answer": "Station",
        "explanation": "えき (eki) means train station.",
        "label": "Week_2"
      },
      {
        "id": "auto_47",
        "question": "Translate: |'What time is it now?'|",
        "choices": [
          "いまなんじですか",
          "いまなんようびですか",
          "いまどこですか",
          "いまいくらですか"
        ],
        "answer": "いまなんじですか",
        "explanation": "何時 (nanji) is the interrogative used for time.",
        "label": "Week_2"
      },
      {
        "id": "auto_48",
        "question": "Which particle is used to mean |'and'| between nouns?",
        "choices": [
          "は",
          "と",
          "に",
          "で"
        ],
        "answer": "と",
        "explanation": "と is used to connect nouns together.",
        "label": "Week_2"
      },
      {
        "id": "auto_49",
        "question": "What is the reading of |五|?",
        "choices": [
          "よん",
          "ご",
          "ろく",
          "しち"
        ],
        "answer": "ご",
        "explanation": "五 is the kanji for the number 5.",
        "label": "Week_2"
      },
      {
        "id": "w2-057",
        "question": "Identify the meaning of |じてんしゃ|.",
        "choices": [
          "Car",
          "Bicycle",
          "Ship",
          "Bus"
        ],
        "answer": "Bicycle",
        "explanation": "じてんしゃ (jitensha) means bicycle.",
        "label": "Week_2"
      },
      {
        "id": "auto_50",
        "question": "Which verb means |'to watch'| or |'to see'|?",
        "choices": [
          "ききます",
          "みます",
          "よみます",
          "たべます"
        ],
        "answer": "みます",
        "explanation": "みます (mimasu) means to see, watch, or look.",
        "label": "Week_2"
      },
      {
        "id": "auto_51",
        "question": "Translate: 'I study |at the library|.' Which particle marks the location of the action?",
        "choices": [
          "に",
          "へ",
          "で",
          "を"
        ],
        "answer": "で",
        "explanation": "The particle で is used to mark the location where an action takes place.",
        "label": "Week_2"
      },
      {
        "id": "w2-060",
        "question": "What is the reading of |三|?",
        "choices": [
          "いち",
          "に",
          "さん",
          "よん"
        ],
        "answer": "さん",
        "explanation": "三 is the kanji for the number 3.",
        "label": "Week_2"
      },
      {
        "id": "auto_52",
        "question": "Identify the meaning of |くるま|.",
        "choices": [
          "Train",
          "Car",
          "Bicycle",
          "Airplane"
        ],
        "answer": "Car",
        "explanation": "くるま (kuruma) means car.",
        "label": "Week_2"
      },
      {
        "id": "auto_53",
        "question": "Which verb means |'to drink'|?",
        "choices": [
          "たべます",
          "のみます",
          "よみます",
          "みます"
        ],
        "answer": "のみます",
        "explanation": "のみます (nomimasu) means to drink.",
        "label": "Week_2"
      },
      {
        "id": "auto_54",
        "question": "Translate: |'I go to Japan.'|",
        "choices": [
          "日本へいきます",
          "日本をいきます",
          "日本でいきます",
          "日本といきます"
        ],
        "answer": "日本へいきます",
        "explanation": "へ marks the destination for movement verbs like いきます.",
        "label": "Week_2"
      },
      {
        "id": "auto_55",
        "question": "What is the reading of |八|?",
        "choices": [
          "ろく",
          "しち",
          "はち",
          "きゅう"
        ],
        "answer": "はち",
        "explanation": "八 is the kanji for the number 8.",
        "label": "Week_2"
      },
      {
        "id": "auto_56",
        "question": "Identify the meaning of |くつ|.",
        "choices": [
          "Tie",
          "Bag",
          "Shoes",
          "Umbrella"
        ],
        "answer": "Shoes",
        "explanation": "くつ (kutsu) means shoes.",
        "label": "Week_2"
      },
      {
        "id": "auto_57",
        "question": "Which particle connects a |person| to a destination in: 'ともだち... うちへ いきます'?",
        "choices": [
          "に",
          "と",
          "を",
          "で"
        ],
        "answer": "と",
        "explanation": "と indicates the companion with whom the action is performed.",
        "label": "Week_2"
      },
      {
        "id": "w2-067",
        "question": "What is the reading of |一|?",
        "choices": [
          "いち",
          "に",
          "さん",
          "し"
        ],
        "answer": "いち",
        "explanation": "一 is the kanji for the number 1.",
        "label": "Week_2"
      },
      {
        "id": "auto_58",
        "question": "Identify the meaning of |しんかんせん|.",
        "choices": [
          "Train",
          "Subway",
          "Bullet train",
          "Taxi"
        ],
        "answer": "Bullet train",
        "explanation": "しんかんせん (shinkansen) is the Japanese high-speed bullet train.",
        "label": "Week_2"
      },
      {
        "id": "w2-069",
        "question": "Which verb means |'to start'| or |'to begin'|?",
        "choices": [
          "はじまります",
          "おわります",
          "べんきょうします",
          "やすみます"
        ],
        "answer": "はじまります",
        "explanation": "はじまります (hajimarimasu) means to begin.",
        "label": "Week_2"
      },
      {
        "id": "auto_59",
        "question": "Translate: |'What is your birthday?'|",
        "choices": [
          "たんじょうびはいつですか",
          "たんじょうびはどこですか",
          "たんじょうびはなんじですか",
          "たんじょうびはいくらですか"
        ],
        "answer": "たんじょうびはいつですか",
        "explanation": "いつ (itsu) is used to ask when something occurs, such as a birthday.",
        "label": "Week_2"
      },
      {
        "id": "auto_60",
        "question": "What is the reading of |七|?",
        "choices": [
          "ろく",
          "しち",
          "はち",
          "きゅう"
        ],
        "answer": "しち",
        "explanation": "七 is the kanji for the number 7.",
        "label": "Week_2"
      },
      {
        "id": "auto_61",
        "question": "Identify the meaning of |ねくたい|.",
        "choices": [
          "Shirt",
          "Tie",
          "Bag",
          "Shoes"
        ],
        "answer": "Tie",
        "explanation": "ねくたい (nekutai) means necktie.",
        "label": "Week_2"
      },
      {
        "id": "auto_62",
        "question": "Which particle marks the |topic| of the sentence?",
        "choices": [
          "は",
          "を",
          "に",
          "で"
        ],
        "answer": "は",
        "explanation": "は is the topic marker particle.",
        "label": "Week_2"
      },
      {
        "id": "auto_63",
        "question": "What is the reading of |四|?",
        "choices": [
          "さん",
          "し",
          "ご",
          "ろく"
        ],
        "answer": "し",
        "explanation": "四 is the kanji for the number 4.",
        "label": "Week_2"
      },
      {
        "id": "auto_64",
        "question": "Identify the meaning of |ばんごう|.",
        "choices": [
          "Name",
          "Address",
          "Number",
          "Time"
        ],
        "answer": "Number",
        "explanation": "ばんごう (bangou) means number (like a phone number).",
        "label": "Week_2"
      },
      {
        "id": "auto_65",
        "question": "Which verb means |'to wake up'|?",
        "choices": [
          "おきます",
          "ねます",
          "たべます",
          "のみます"
        ],
        "answer": "おきます",
        "explanation": "おきます (okimasu) means to wake up.",
        "label": "Week_2"
      },
      {
        "id": "auto_66",
        "question": "What is the reading of |九|?",
        "choices": [
          "しち",
          "はち",
          "きゅう",
          "じゅう"
        ],
        "answer": "きゅう",
        "explanation": "九 is the kanji for the number 9.",
        "label": "Week_2"
      },
      {
        "id": "auto_67",
        "question": "Identify the meaning of |かいだん|.",
        "choices": [
          "Elevator",
          "Staircase",
          "Escalator",
          "Room"
        ],
        "answer": "Staircase",
        "explanation": "かいだん (kaidan) means stairs or staircase.",
        "label": "Week_2"
      },
      {
        "id": "auto_68",
        "question": "Which particle is used to mark |point of origin| in: 'ベトナム... きました'?",
        "choices": [
          "に",
          "から",
          "で",
          "を"
        ],
        "answer": "から",
        "explanation": "から indicates origin or starting point.",
        "label": "Week_2"
      },
      {
        "id": "auto_69",
        "question": "What is the reading of |十|?",
        "choices": [
          "じゅう",
          "きゅう",
          "はち",
          "しち"
        ],
        "answer": "じゅう",
        "explanation": "十 is the kanji for the number 10.",
        "label": "Week_2"
      },
      {
        "id": "auto_70",
        "question": "Identify the meaning of |でんわ|.",
        "choices": [
          "Computer",
          "Television",
          "Telephone",
          "Radio"
        ],
        "answer": "Telephone",
        "explanation": "でんわ (denwa) means telephone.",
        "label": "Week_2"
      },
      {
        "id": "auto_71",
        "question": "Which verb means |'to come'|?",
        "choices": [
          "いきます",
          "きます",
          "かえります",
          "おきます"
        ],
        "answer": "きます",
        "explanation": "きます (kimasu) means to come.",
        "label": "Week_2"
      },
      {
        "id": "auto_72",
        "question": "What is the reading of |日月| in |日曜日| and |月曜日|?",
        "choices": [
          "にち・げつ",
          "か・すい",
          "もく・きん",
          "ど・にち"
        ],
        "answer": "にち・げつ",
        "explanation": "日 is read as にち in 日曜日, and 月 is read as げつ in 月曜日.",
        "label": "Week_2"
      },
      {
        "id": "auto_73",
        "question": "Identify the meaning of |かさ|.",
        "choices": [
          "Shoes",
          "Bag",
          "Umbrella",
          "Tie"
        ],
        "answer": "Umbrella",
        "explanation": "かさ (kasa) means umbrella.",
        "label": "Week_2"
      },
      {
        "id": "auto_74",
        "question": "Which particle indicates the |end point| of time or space?",
        "choices": [
          "から",
          "まで",
          "に",
          "を"
        ],
        "answer": "まで",
        "explanation": "まで indicates the ending point (until).",
        "label": "Week_2"
      },
      {
        "id": "auto_75",
        "question": "What is the reading of |火水| in |火曜日| and |水曜日|?",
        "choices": [
          "にち・げつ",
          "か・すい",
          "もく・きん",
          "ど・にち"
        ],
        "answer": "か・すい",
        "explanation": "火 is read as か, and 水 is read as すい in the context of days of the week.",
        "label": "Week_2"
      },
      {
        "id": "auto_76",
        "question": "Identify the meaning of |かいしゃ|.",
        "choices": [
          "School",
          "Company",
          "Bank",
          "Hospital"
        ],
        "answer": "Company",
        "explanation": "かいしゃ (kaisha) means company or office.",
        "label": "Week_2"
      },
      {
        "id": "auto_77",
        "question": "Which verb means |'to study'|?",
        "choices": [
          "はたらきます",
          "べんきょうします",
          "やすみます",
          "ねます"
        ],
        "answer": "べんきょうします",
        "explanation": "べんきょうします (benkyoushimasu) means to study.",
        "label": "Week_2"
      },
      {
        "id": "auto_78",
        "question": "What is the reading of |木金| in |木曜日| and |金曜日|?",
        "choices": [
          "か・すい",
          "もく・きん",
          "ど・にち",
          "にち・げつ"
        ],
        "answer": "もく・きん",
        "explanation": "木 is read as もく, and 金 is read as きん.",
        "label": "Week_2"
      },
      {
        "id": "auto_79",
        "question": "Identify the meaning of |ぎんこう|.",
        "choices": [
          "School",
          "Bank",
          "Library",
          "Post office"
        ],
        "answer": "Bank",
        "explanation": "ぎんこう (ginkou) means bank.",
        "label": "Week_2"
      },
      {
        "id": "auto_80",
        "question": "Which particle is used to mark the |destination| for |帰ります|?",
        "choices": [
          "に/へ",
          "を",
          "で",
          "と"
        ],
        "answer": "に/へ",
        "explanation": "Either に or へ can be used to indicate the destination of movement.",
        "label": "Week_2"
      },
      {
        "id": "auto_81",
        "question": "What is the reading of |土| in |土曜日|?",
        "choices": [
          "か",
          "すい",
          "ど",
          "にち"
        ],
        "answer": "ど",
        "explanation": "土 is read as ど in the context of Saturday.",
        "label": "Week_2"
      },
      {
        "id": "auto_82",
        "question": "Identify the meaning of |としょかん|.",
        "choices": [
          "Bank",
          "Library",
          "School",
          "Store"
        ],
        "answer": "Library",
        "explanation": "としょかん (toshokan) means library.",
        "label": "Week_2"
      },
      {
        "id": "auto_83",
        "question": "Which verb means |'to take a holiday'| or |'to rest'|?",
        "choices": [
          "はたらきます",
          "やすみます",
          "ねます",
          "おきます"
        ],
        "answer": "やすみます",
        "explanation": "やすみます (yasumimasu) means to rest or take a holiday.",
        "label": "Week_2"
      },
      {
        "id": "auto_84",
        "question": "What is the reading of |人| in |日本人|?",
        "choices": [
          "ひと",
          "じん",
          "にん",
          "ざん"
        ],
        "answer": "じん",
        "explanation": "When used for nationality, 人 is read as じん.",
        "label": "Week_2"
      },
      {
        "id": "auto_85",
        "question": "Identify the meaning of |ゆうびんきょく|.",
        "choices": [
          "Post office",
          "Bank",
          "Police station",
          "Hospital"
        ],
        "answer": "Post office",
        "explanation": "ゆうびんきょく (yuubinkyoku) means post office.",
        "label": "Week_2"
      },
      {
        "id": "auto_86",
        "question": "Which particle is used to indicate |time| when it's not a specific number (e.g. 'tomorrow')?",
        "choices": [
          "に",
          "を",
          "No particle needed",
          "で"
        ],
        "answer": "No particle needed",
        "explanation": "Non-specific time words like あした (tomorrow) do not require particle に.",
        "label": "Week_2"
      },
      {
        "id": "auto_87",
        "question": "What is the reading of |円|?",
        "choices": [
          "えん",
          "まる",
          "さん",
          "じん"
        ],
        "answer": "えん",
        "explanation": "円 is read as えん (en) for currency.",
        "label": "Week_2"
      },
      {
        "id": "auto_88",
        "question": "Identify the meaning of |デパート|.",
        "choices": [
          "Supermarket",
          "Convenience store",
          "Department store",
          "Market"
        ],
        "answer": "Department store",
        "explanation": "デパート (depa-to) means department store.",
        "label": "Week_2"
      },
      {
        "id": "auto_89",
        "question": "Which verb means |'to go'|?",
        "choices": [
          "いきます",
          "きます",
          "かえります",
          "ねます"
        ],
        "answer": "いきます",
        "explanation": "いきます (ikimasu) means to go.",
        "label": "Week_2"
      }
    ],
    "kanji": {
      "学": {
        "reading": "がく, まな(ぶ)",
        "meaning": "study, learning",
        "label": "Week_2"
      },
      "校": {
        "reading": "こう",
        "meaning": "school",
        "label": "Week_2"
      },
      "車": {
        "reading": "しゃ, くるま",
        "meaning": "car, vehicle",
        "label": "Week_2"
      },
      "日": {
        "reading": "にち/ひ",
        "meaning": "Day/Sun",
        "label": "Week_2"
      },
      "本": {
        "reading": "ほん, もと",
        "meaning": "book, origin",
        "label": "Week_2"
      },
      "語": {
        "reading": "ご, かた(る)",
        "meaning": "language, word",
        "label": "Week_2"
      },
      "毎": {
        "reading": "まい",
        "meaning": "every",
        "label": "Week_2"
      },
      "一": {
        "reading": "いち",
        "meaning": "One",
        "label": "Week_2"
      },
      "二": {
        "reading": "に",
        "meaning": "Two",
        "label": "Week_2"
      },
      "三": {
        "reading": "さん",
        "meaning": "Three",
        "label": "Week_2"
      },
      "四": {
        "reading": "し/よん",
        "meaning": "Four",
        "label": "Week_2"
      },
      "五": {
        "reading": "ご",
        "meaning": "Five",
        "label": "Week_2"
      },
      "六": {
        "reading": "ろく",
        "meaning": "Six",
        "label": "Week_2"
      },
      "七": {
        "reading": "しち/なな",
        "meaning": "Seven",
        "label": "Week_2"
      },
      "八": {
        "reading": "はち",
        "meaning": "Eight",
        "label": "Week_2"
      },
      "九": {
        "reading": "く/きゅう",
        "meaning": "Nine",
        "label": "Week_2"
      },
      "十": {
        "reading": "じゅう",
        "meaning": "Ten",
        "label": "Week_2"
      },
      "月": {
        "reading": "げつ/つき",
        "meaning": "Month/Moon",
        "label": "Week_2"
      },
      "火": {
        "reading": "か/ひ",
        "meaning": "Fire",
        "label": "Week_2"
      },
      "水": {
        "reading": "すい/みず",
        "meaning": "Water",
        "label": "Week_2"
      },
      "木": {
        "reading": "もく/き",
        "meaning": "Tree/Wood",
        "label": "Week_2"
      },
      "金": {
        "reading": "きん/かね",
        "meaning": "Gold/Money",
        "label": "Week_2"
      },
      "土": {
        "reading": "ど/つち",
        "meaning": "Earth/Soil",
        "label": "Week_2"
      },
      "人": {
        "reading": "じん/ひと",
        "meaning": "Person",
        "label": "Week_2"
      },
      "円": {
        "reading": "えん",
        "meaning": "Yen/Circle",
        "label": "Week_2"
      },
      "山": {
        "reading": "さん/やま",
        "meaning": "Mountain",
        "label": "Week_2"
      },
      "行": {
        "reading": "こう, い(く), おこな(う)",
        "meaning": "go, conduct",
        "label": "Week_2"
      },
      "時": {
        "reading": "じ, とき",
        "meaning": "time, hour",
        "label": "Week_2"
      },
      "曜": {
        "reading": "よう",
        "meaning": "weekday",
        "label": "Week_2"
      },
      "電": {
        "reading": "でん",
        "meaning": "electricity",
        "label": "Week_2"
      },
      "何": {
        "reading": "なに, なん",
        "meaning": "what",
        "label": "Week_2"
      },
      "起": {
        "reading": "き, お(きる)",
        "meaning": "wake up, rise",
        "label": "Week_2"
      },
      "寝": {
        "reading": "しん, ね(る)",
        "meaning": "sleep, lie down",
        "label": "Week_2"
      },
      "来": {
        "reading": "らい, く(る)",
        "meaning": "come",
        "label": "Week_2"
      },
      "帰": {
        "reading": "き, かえ(る)",
        "meaning": "return home",
        "label": "Week_2"
      },
      "食": {
        "reading": "しょく, た(べる)",
        "meaning": "eat, food",
        "label": "Week_2"
      },
      "飲": {
        "reading": "いん, の(む)",
        "meaning": "drink",
        "label": "Week_2"
      },
      "読": {
        "reading": "どく, よ(む)",
        "meaning": "read",
        "label": "Week_2"
      },
      "見": {
        "reading": "けん, み(る)",
        "meaning": "see, look",
        "label": "Week_2"
      },
      "働": {
        "reading": "どう, はたら(く)",
        "meaning": "work",
        "label": "Week_2"
      },
      "会": {
        "reading": "かい, あ(う)",
        "meaning": "meeting, meet",
        "label": "Week_2"
      },
      "社": {
        "reading": "しゃ",
        "meaning": "company, shrine",
        "label": "Week_2"
      },
      "駅": {
        "reading": "えき",
        "meaning": "station",
        "label": "Week_2"
      },
      "自": {
        "reading": "じ, し",
        "meaning": "self",
        "label": "Week_2"
      },
      "転": {
        "reading": "てん, ころ(がる)",
        "meaning": "turn, roll",
        "label": "Week_2"
      },
      "飛": {
        "reading": "ひ, と(ぶ)",
        "meaning": "fly",
        "label": "Week_2"
      },
      "機": {
        "reading": "き",
        "meaning": "machine, opportunity",
        "label": "Week_2"
      },
      "幹": {
        "reading": "かん, みき",
        "meaning": "trunk, main",
        "label": "Week_2"
      },
      "線": {
        "reading": "せん",
        "meaning": "line",
        "label": "Week_2"
      },
      "千": {
        "reading": "せん, ち",
        "meaning": "thousand",
        "label": "Week_2"
      },
      "今": {
        "reading": "こん, いま",
        "meaning": "now",
        "label": "Week_2"
      },
      "午": {
        "reading": "ご",
        "meaning": "noon",
        "label": "Week_2"
      },
      "前": {
        "reading": "ぜん, まえ",
        "meaning": "before, front",
        "label": "Week_2"
      },
      "後": {
        "reading": "ご, こう, あと, うし(ろ)",
        "meaning": "after, behind",
        "label": "Week_2"
      },
      "半": {
        "reading": "はん",
        "meaning": "half",
        "label": "Week_2"
      },
      "分": {
        "reading": "ふん, ぶん, わ(ける)",
        "meaning": "minute, part",
        "label": "Week_2"
      },
      "明": {
        "reading": "めい, あ(かり)",
        "meaning": "bright, next",
        "label": "Week_2"
      },
      "昨": {
        "reading": "さく, きのう",
        "meaning": "last (year), yesterday",
        "label": "Week_2"
      }
    },
    "words": {
      "学校": {
        "reading": "がっこう",
        "meaning": "school",
        "label": "Week_2"
      },
      "日本語": {
        "reading": "にほんご",
        "meaning": "Japanese language",
        "label": "Week_2"
      },
      "月曜日": {
        "reading": "げつようび",
        "meaning": "Monday",
        "label": "Week_2"
      },
      "火曜日": {
        "reading": "かようび",
        "meaning": "Tuesday",
        "label": "Week_2"
      },
      "水曜日": {
        "reading": "すいようび",
        "meaning": "Wednesday",
        "label": "Week_2"
      },
      "木曜日": {
        "reading": "もくようび",
        "meaning": "Thursday",
        "label": "Week_2"
      },
      "金曜日": {
        "reading": "きんようび",
        "meaning": "Friday",
        "label": "Week_2"
      },
      "土曜日": {
        "reading": "どようび",
        "meaning": "Saturday",
        "label": "Week_2"
      },
      "日曜日": {
        "reading": "にちようび",
        "meaning": "Sunday",
        "label": "Week_2"
      },
      "何曜日": {
        "reading": "なんようび",
        "meaning": "what day of the week",
        "label": "Week_2"
      },
      "何時": {
        "reading": "なんじ",
        "meaning": "what time",
        "label": "Week_2"
      },
      "毎日": {
        "reading": "まいにち",
        "meaning": "every day",
        "label": "Week_2"
      },
      "毎朝": {
        "reading": "まいあさ",
        "meaning": "every morning",
        "label": "Week_2"
      },
      "毎晩": {
        "reading": "まいばん",
        "meaning": "every night",
        "label": "Week_2"
      },
      "今": {
        "reading": "いま",
        "meaning": "now",
        "label": "Week_2"
      },
      "午前": {
        "reading": "ごぜん",
        "meaning": "AM, morning",
        "label": "Week_2"
      },
      "午後": {
        "reading": "ごご",
        "meaning": "PM, afternoon",
        "label": "Week_2"
      },
      "半": {
        "reading": "はん",
        "meaning": "half (used for :30)",
        "label": "Week_2"
      },
      "起きます": {
        "reading": "おきます",
        "meaning": "to wake up, get up",
        "label": "Week_2"
      },
      "寝ます": {
        "reading": "ねます",
        "meaning": "to sleep, go to bed",
        "label": "Week_2"
      },
      "行きます": {
        "reading": "いきます",
        "meaning": "to go",
        "label": "Week_2"
      },
      "来ます": {
        "reading": "きます",
        "meaning": "to come",
        "label": "Week_2"
      },
      "帰ります": {
        "reading": "かえります",
        "meaning": "to return home",
        "label": "Week_2"
      },
      "食べます": {
        "reading": "たべます",
        "meaning": "to eat",
        "label": "Week_2"
      },
      "飲みます": {
        "reading": "のみます",
        "meaning": "to drink",
        "label": "Week_2"
      },
      "読みます": {
        "reading": "よみます",
        "meaning": "to read",
        "label": "Week_2"
      },
      "見ます": {
        "reading": "みます",
        "meaning": "to watch, see",
        "label": "Week_2"
      },
      "聞きます": {
        "reading": "ききます",
        "meaning": "to listen, hear, ask",
        "label": "Week_2"
      },
      "働きます": {
        "reading": "はたらきます",
        "meaning": "to work",
        "label": "Week_2"
      },
      "休みます": {
        "reading": "やすみます",
        "meaning": "to rest, take off",
        "label": "Week_2"
      },
      "電車": {
        "reading": "でんしゃ",
        "meaning": "train",
        "label": "Week_2"
      },
      "新幹線": {
        "reading": "しんかんせん",
        "meaning": "bullet train",
        "label": "Week_2"
      },
      "自転車": {
        "reading": "じてんしゃ",
        "meaning": "bicycle",
        "label": "Week_2"
      },
      "飛行機": {
        "reading": "ひこうき",
        "meaning": "airplane",
        "label": "Week_2"
      },
      "駅": {
        "reading": "えき",
        "meaning": "(train) station",
        "label": "Week_2"
      },
      "会社": {
        "reading": "かいしゃ",
        "meaning": "company",
        "label": "Week_2"
      },
      "ここ": {
        "reading": "ここ",
        "meaning": "here (near speaker)",
        "label": "Week_2"
      },
      "そこ": {
        "reading": "そこ",
        "meaning": "there (near listener)",
        "label": "Week_2"
      },
      "あそこ": {
        "reading": "あそこ",
        "meaning": "over there (far from both)",
        "label": "Week_2"
      },
      "どこ": {
        "reading": "どこ",
        "meaning": "where",
        "label": "Week_2"
      },
      "いくら": {
        "reading": "いくら",
        "meaning": "how much (price)",
        "label": "Week_2"
      },
      "新": {
        "reading": "しん , あたら(しい)",
        "meaning": "new",
        "label": "Week_2"
      },
      "車": {
        "reading": "しゃ , くるま",
        "meaning": "car / wheel / vehicle",
        "label": "Week_2"
      },
      "山": {
        "reading": "さん , やま",
        "meaning": "mountain",
        "label": "Week_2"
      },
      "人": {
        "reading": "じん, にん , ひと",
        "meaning": "person",
        "label": "Week_2"
      },
      "円": {
        "reading": "えん , まる(い)",
        "meaning": "yen / circle / round",
        "label": "Week_2"
      },
      "9時": {
        "reading": "くじ",
        "meaning": "9 o'clock (exception: くじ, not きゅうじ)",
        "label": "Week_2"
      },
      "4時": {
        "reading": "よじ",
        "meaning": "4 o'clock (exception: よじ, not しじ)",
        "label": "Week_2"
      },
      "7時": {
        "reading": "しちじ",
        "meaning": "7 o'clock",
        "label": "Week_2"
      },
      "一": {
        "reading": "いち , ひと(つ)",
        "meaning": "one",
        "label": "Week_2"
      },
      "二": {
        "reading": "に , ふた(つ)",
        "meaning": "two",
        "label": "Week_2"
      },
      "三": {
        "reading": "さん , みっ(つ)",
        "meaning": "three",
        "label": "Week_2"
      },
      "五": {
        "reading": "ご , いつ(つ)",
        "meaning": "five",
        "label": "Week_2"
      },
      "七": {
        "reading": "しち, なな , なな(つ)",
        "meaning": "seven",
        "label": "Week_2"
      },
      "九": {
        "reading": "きゅう, く , ここの(つ)",
        "meaning": "nine",
        "label": "Week_2"
      },
      "十": {
        "reading": "じゅう , とお",
        "meaning": "ten",
        "label": "Week_2"
      },
      "日": {
        "reading": "にち, じつ , ひ, か",
        "meaning": "day / sun",
        "label": "Week_2"
      },
      "月": {
        "reading": "げつ, がつ , つき",
        "meaning": "month / moon",
        "label": "Week_2"
      },
      "火": {
        "reading": "か , ひ",
        "meaning": "fire",
        "label": "Week_2"
      },
      "水": {
        "reading": "すい , みず",
        "meaning": "water",
        "label": "Week_2"
      },
      "木": {
        "reading": "もく, ぼく , き",
        "meaning": "tree / wood",
        "label": "Week_2"
      },
      "金": {
        "reading": "きん, こん , かね",
        "meaning": "gold / money",
        "label": "Week_2"
      },
      "土": {
        "reading": "ど, と , つち",
        "meaning": "soil / earth / ground",
        "label": "Week_2"
      },
      "お金": {
        "reading": "おかね",
        "meaning": "money",
        "label": "Week_2"
      },
      "日本": {
        "reading": "にほん, にっぽん",
        "meaning": "Japan",
        "label": "Week_2"
      },
      "日本人": {
        "reading": "にほんじん",
        "meaning": "Japanese person",
        "label": "Week_2"
      },
      "三人": {
        "reading": "さんにん",
        "meaning": "three people",
        "label": "Week_2"
      },
      "一人": {
        "reading": "ひとり",
        "meaning": "one person; alone (exception)",
        "label": "Week_2"
      },
      "二人": {
        "reading": "ふたり",
        "meaning": "two people (exception)",
        "label": "Week_2"
      },
      "四人": {
        "reading": "よにん",
        "meaning": "four people",
        "label": "Week_2"
      },
      "千円": {
        "reading": "せんえん",
        "meaning": "1000 yen",
        "label": "Week_2"
      },
      "三つ": {
        "reading": "みっつ",
        "meaning": "three (general counter)",
        "label": "Week_2"
      },
      "四つ": {
        "reading": "よっつ",
        "meaning": "four (general counter)",
        "label": "Week_2"
      },
      "1時": {
        "reading": "いちじ",
        "meaning": "1 o'clock",
        "label": "Week_2"
      },
      "10時半": {
        "reading": "じゅうじはん",
        "meaning": "10:30",
        "label": "Week_2"
      },
      "4月": {
        "reading": "しがつ",
        "meaning": "April",
        "label": "Week_2"
      },
      "7月": {
        "reading": "しちがつ",
        "meaning": "July",
        "label": "Week_2"
      },
      "9月": {
        "reading": "くがつ",
        "meaning": "September",
        "label": "Week_2"
      },
      "30分": {
        "reading": "さんじゅっぷん",
        "meaning": "30 minutes",
        "label": "Week_2"
      },
      "じむしょ": {
        "reading": "じむしょ",
        "meaning": "Office",
        "label": "Week_2"
      },
      "うけつけ": {
        "reading": "うけつけ",
        "meaning": "Reception desk",
        "label": "Week_2"
      },
      "でんしゃ": {
        "reading": "でんしゃ",
        "meaning": "Train",
        "label": "Week_2"
      },
      "じてんしゃ": {
        "reading": "じてんしゃ",
        "meaning": "Bicycle",
        "label": "Week_2"
      },
      "はたらきます": {
        "reading": "はたらきます",
        "meaning": "To work",
        "label": "Week_2"
      },
      "べんきょうします": {
        "reading": "べんきょうします",
        "meaning": "To study",
        "label": "Week_2"
      },
      "おきます": {
        "reading": "おきます",
        "meaning": "To wake up",
        "label": "Week_2"
      },
      "ねます": {
        "reading": "ねます",
        "meaning": "To sleep",
        "label": "Week_2"
      },
      "いきます": {
        "reading": "いきます",
        "meaning": "To go",
        "label": "Week_2"
      },
      "きます": {
        "reading": "きます",
        "meaning": "To come",
        "label": "Week_2"
      },
      "かえります": {
        "reading": "かえります",
        "meaning": "To return home",
        "label": "Week_2"
      },
      "たべます": {
        "reading": "たべます",
        "meaning": "To eat",
        "label": "Week_2"
      },
      "のみます": {
        "reading": "のみます",
        "meaning": "To drink",
        "label": "Week_2"
      }
    }
  }
};
